# Generated by Django 3.2 on 2023-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.TextField()),
                ('released_date', models.DateField()),
                ('poster_path', models.TextField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.IntegerField()),
                ('overview', models.TextField()),
                ('genres', models.JSONField()),
            ],
        ),
    ]
