# Generated by Django 3.2.18 on 2023-05-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contain_movies',
            field=models.ManyToManyField(related_name='contain_articles', to='movies.Movie'),
        ),
    ]
