# Generated by Django 3.2.18 on 2023-05-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
